// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv75mAR7AKWfnbJd1TQ0WdO_-eQ-J7wAI',
    appId: '1:888363249168:web:c5d0c9558e49a3713c6495',
    messagingSenderId: '888363249168',
    projectId: 'neoncode-40059',
    authDomain: 'neoncode-40059.firebaseapp.com',
    storageBucket: 'neoncode-40059.firebasestorage.app',
    measurementId: 'G-J5B6QD0N25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDncex1g2UaXjM8vibfEUXsD2oBNqmQg2g',
    appId: '1:888363249168:android:8be9f066578d7cd73c6495',
    messagingSenderId: '888363249168',
    projectId: 'neoncode-40059',
    storageBucket: 'neoncode-40059.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh-YAX1vZQbol_YEQ114M0OMzIQautbAY',
    appId: '1:888363249168:ios:a6890728787ae4563c6495',
    messagingSenderId: '888363249168',
    projectId: 'neoncode-40059',
    storageBucket: 'neoncode-40059.firebasestorage.app',
    iosBundleId: 'com.example.cacaoAiFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh-YAX1vZQbol_YEQ114M0OMzIQautbAY',
    appId: '1:888363249168:ios:a6890728787ae4563c6495',
    messagingSenderId: '888363249168',
    projectId: 'neoncode-40059',
    storageBucket: 'neoncode-40059.firebasestorage.app',
    iosBundleId: 'com.example.cacaoAiFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv75mAR7AKWfnbJd1TQ0WdO_-eQ-J7wAI',
    appId: '1:888363249168:web:fef3923e1c01b0703c6495',
    messagingSenderId: '888363249168',
    projectId: 'neoncode-40059',
    authDomain: 'neoncode-40059.firebaseapp.com',
    storageBucket: 'neoncode-40059.firebasestorage.app',
    measurementId: 'G-7LRQD7ECBT',
  );
}
